import { NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';
import { supabase } from '@/lib/supabase';

// Helper to get authenticated client
const getAuthenticatedSupabase = (token: string) => {
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || 'https://placeholder.supabase.co';
  const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || 'placeholder-anon-key';
  return createClient(supabaseUrl, supabaseAnonKey, {
    global: { headers: { Authorization: `Bearer ${token}` } },
  });
};

export async function POST(request: Request) {
  try {
    const { title, date, content, status, location } = await request.json();

    // Check for Authorization header
    const authHeader = request.headers.get('Authorization');
    if (!authHeader) {
      return NextResponse.json(
        { error: 'Unauthorized' },
        { status: 401 }
      );
    }

    const token = authHeader.replace('Bearer ', '');
    const { data: { user }, error: authError } = await supabase.auth.getUser(token);

    if (authError || !user) {
      return NextResponse.json(
        { error: 'Unauthorized' },
        { status: 401 }
      );
    }

    if (!title || !date || !content) {
      return NextResponse.json(
        { error: 'Missing required fields' },
        { status: 400 }
      );
    }

    const slug = title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/(^-|-$)+/g, '');

    const supabaseAuthenticated = getAuthenticatedSupabase(token);

    const insertData: any = {
      slug,
      title,
      date,
      content,
      status: status || 'draft',
      created_by: user.id,
    };

    // Only include location if it's provided
    if (location) {
      insertData.location = location;
    }

    const { data, error } = await supabaseAuthenticated.from('posts').insert(insertData);

    if (error) {
        console.error('Supabase insert error:', {
          message: error.message,
          details: (error as any).details,
          hint: (error as any).hint,
          code: (error as any).code,
        });
        return NextResponse.json({ error: 'Supabase insert error', details: error.message }, { status: 500 });
    }

    // Return the inserted slug (server-side data may include autogenerated fields)
    const returnedSlug = Array.isArray(data) && data[0] ? (data[0] as any).slug || slug : slug;
    return NextResponse.json({ success: true, slug: returnedSlug });
  } catch (error) {
    console.error('Error saving post:', error);
    return NextResponse.json(
      { error: 'Failed to save post' },
      { status: 500 }
    );
  }
}

export async function GET(request: Request) {
  try {
    const authHeader = request.headers.get('Authorization');
    if (!authHeader) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const token = authHeader.replace('Bearer ', '');
    const { data: { user }, error: authError } = await supabase.auth.getUser(token);

    if (authError || !user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const supabaseAuthenticated = getAuthenticatedSupabase(token);

    // Fetch posts created by this user
    const { data, error } = await supabaseAuthenticated
      .from('posts')
      .select('id, slug, title, date, status, location, created_at')
      .eq('created_by', user.id)
      .order('date', { ascending: false });

    if (error) {
      throw error;
    }

    return NextResponse.json({ posts: data });
  } catch (error) {
    console.error('Error fetching user posts:', error);
    return NextResponse.json(
      { error: 'Failed to fetch posts' },
      { status: 500 }
    );
  }
}
